### ISSUE TITLE
ctl-Tag performance

### ISSUE THREAD

**Issue by JLabisch** [drventure/Disambiguator#2] opened 2021-06-01 10:16 UTC
The ctl-functionality is exactly what I was looking for.
When I include it in two entries, keepass is slowed down so much that autotype not usable any more. The matching takes several minutes to complete.
I had to de-install it.

**Comment by drventure** [comment] 2021-06-05 02:29
Hmm. Very strange. I use it all the time myself and have never noticed any issues like that.
I'm using 2.47 of Keepass. Is that what you're on?
Also, if you don't mind sharing, what App and control were you trying to disambiguate? and how did you enter the tags in keepass?

That might help me narrow things down.

For EXE disambiguation, I can't imagine anything would slow the process down that much. The app just checks the target app exe name against the tag.

For controls, it +might+ slow down because of tons of controls in the target app, but even that would surprise me. The enumeration of controls typically happens almost instantly.

Only share if you want to, and of course, don't share actual passwords, the Keepass DB or anything else like that.

Thanks!

**Comment by JLabisch** [comment] 2021-06-08 12:52
It was controls, not exe.
I had two different web pages in firefox as targets. 
I found the tags by try/error from the message window you provided.
The first entry was fine, but when I entered the second match for a different entry the performance went down.
IIRC  every menu entry etc. was checked, including the shortcuts, which can be a lot. Do you filter controls with enterable inputs?
This is just out of my head, as I have no time to test this week. Maybe end of this week or next week... just wanted to give you some feedback

**Comment by drventure** [comment] 2023-06-11 22:01
Hi
Just wanted to get back with you on this. I've posted an update, 1.0.2, that might help.

It should be considerably faster to resolve controls in the target app now.

Main issue was that the controls tree was being traversed repeatedly, which was unnecessary.

**Comment by drventure** [comment] 2023-07-01 21:21
Just posted another update, 1.0.3
With a little help from another user, I believe we were able to isolate the cause of the slowness.
It should be corrected in this release.
This release also includes a logging feature. If it's still slow, and you have time, could you turn logging on and then perform the autotype?

The log only captures window titles and match patterns, no passwords, usernames etc.

Each line is date time stamped, so you'd want to look for any two lines where there's a significant delay between them.

If you prefer, you could email me the log or just post a small snippet of what you find here.

But again, the 1.0.3 release should address the performance, so you may no longer see a slowdown.

**Comment by drventure** [comment] 2023-07-22 21:40
Since I was able to replicate this issue and it appears to be corrected in 1.0.3/1.0.4, I'm going to close this issue now. If it still seems to be a problem, feel free to reopen or let me know.

**Closed as completed by drventure** 2023-07-22 21:40 UTC
